# Generated by Django 2.2.4 on 2019-08-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('is_boast', models.BooleanField(default=True)),
                ('upvote_counts', models.IntegerField()),
                ('downvote_counts', models.IntegerField()),
            ],
        ),
    ]
