# Generated by Django 2.2.4 on 2019-08-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='magic_string',
            field=models.CharField(default='XvE1f9', max_length=6),
        ),
    ]
