# Generated by Django 2.2.4 on 2019-08-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='downvote_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvote_counts',
            field=models.IntegerField(default=0),
        ),
    ]
